language: ruby
cache: bundler
script: 'bundle exec rake'
rvm:
  - 2.2.5
services:
  - mongodb

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never

matrix:
  include:
    - rvm: 2.3.3
      env: MONGOID_VERSION=5
    - rvm: 2.3.3
      env: MONGOID_VERSION=6
    - rvm: 2.5.0
      env: MONGOID_VERSION=7
